name: idp
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - libcxx=14.0.6
  - libffi=3.3
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.2.2
  - python=3.10.6
  - readline=8.2
  - sqlite=3.39.3
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - pip:
    - altair==4.2.0
    - attrs==22.1.0
    - biopython==1.79
    - blinker==1.5
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - commonmark==0.9.1
    - contourpy==1.0.5
    - cycler==0.11.0
    - decorator==5.1.1
    - entrypoints==0.4
    - exceptiongroup==1.0.4
    - fonttools==4.37.4
    - gitdb==4.0.9
    - gitpython==3.1.29
    - idna==3.4
    - importlib-metadata==5.0.0
    - iniconfig==1.1.1
    - jinja2==3.1.2
    - jsonschema==4.16.0
    - kiwisolver==1.4.4
    - markupsafe==2.1.1
    - matplotlib==3.6.0
    - numpy==1.23.4
    - packaging==21.3
    - pandas==1.5.1
    - pillow==9.2.0
    - pluggy==1.0.0
    - protobuf==3.20.3
    - pyarrow==9.0.0
    - pydeck==0.8.0b4
    - pygments==2.13.0
    - pympler==1.0.1
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pytest==7.2.0
    - python-dateutil==2.8.2
    - pytz==2022.5
    - pytz-deprecation-shim==0.1.0.post0
    - requests==2.28.1
    - rich==12.6.0
    - scipy==1.9.2
    - seaborn==0.12.1
    - semver==2.13.0
    - setuptools==63.4.1
    - six==1.16.0
    - smmap==5.0.0
    - streamlit==1.13.0
    - toml==0.10.2
    - tomli==2.0.1
    - toolz==0.12.0
    - tornado==6.2
    - tqdm==4.64.1
    - typing-extensions==4.4.0
    - tzdata==2022.5
    - tzlocal==4.2
    - urllib3==1.26.12
    - validators==0.20.0
    - watchdog==2.1.9
    - zipp==3.9.0
