name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # our project requires APIs from Python 3.10
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: tester-env
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --prune
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        conda activate tester-env
        pylint $(git ls-files '*.py')
